export const lineStyles = {
    'Transmission Lines Capacity < 132 kV': { color: 'yellow', weight: 2 },
    'Transmission Lines Capacity 132-220 kV': { color: 'orange', weight: 3 },
    'Transmission Lines Capacity 220-500 kV': { color: 'red', weight: 4 },
    'Transmission Lines Capacity >= 500 kV': { color: 'purple', weight: 5 },
    'Gas Pipelines Gas Pipeline': { color: 'grey', weight: 3 },
    'Gas Pipelines Proposed Gas Pipeline': { color: 'grey', dashArray: '5, 5', weight: 3 },
    'Oil Pipelines Oil pipeline': { color: 'black', weight: 3 },
    'Oil Pipelines Proposed Oil pipeline': { color: 'black', dashArray: '5, 5', weight: 3 },
    'Railway Lines Operational': { color: 'blue', weight: 2 },
    'Railway Lines Abandoned': { color: 'blue', dashArray: '3, 3', weight: 1 },
    'Railway Lines Dismantled': { color: 'blue', dashArray: '1, 5', weight: 1 }
};

export const icons = {
    'Airports Small Airport': '/assets/images/airport1.png',
    'Airports Medium Airport': '/assets/images/airport2.png',
    'Airports Large Airport': '/assets/images/airport3.png',
    'Airports Heliport': '/assets/images/heliport.png',
    'Liquid Fuel Terminals Operational': '/assets/images/fuel_terminal1.png',
    'Liquid Fuel Terminals Decommissioned': '/assets/images/fuel_terminal2.png',
    'Railway Stations Operational': '/assets/images/railway_station1.png',
    'Railway Stations Abandoned': '/assets/images/railway_station2.png',
    'Railway Stations Disused': '/assets/images/railway_station3.png',
    'Major Power Stations Water': '/assets/images/power_station_blue.png',
    'Major Power Stations Wind': '/assets/images/power_station_aqua.png',
    'Major Power Stations Natural Gas': '/assets/images/power_station_lgrey.png',
    'Major Power Stations Coal': '/assets/images/power_station_black.png',
    'Major Power Stations Solar': '/assets/images/power_station_yellow.png',
    'Major Power Stations Biogas': '/assets/images/power_station_green.png',
    'Major Power Stations Distillate': '/assets/images/power_station_purple.png',
    'Major Power Stations Biomass': '/assets/images/power_station_brown.png',
    'Major Power Stations Coal Seam Methane': '/assets/images/power_station_dgrey.png',
    'Major Power Stations Other': '/assets/images/power_station_pink.png',
    'Transmission Substation Substations': '/assets/images/substation1.png',
    'Transmission Substation Zone': '/assets/images/substation2.png',
    'Transmission Substation Terminal': '/assets/images/substation3.png',
    'Transmission Substation Switchyard': '/assets/images/substation4.png',
    'Transmission Substation Transmission': '/assets/images/substation5.png',
    'Waste Management C&D Waste Recycling Facility': '/assets/images/waste_management1.png',
    'Waste Management Putrescible Landfill': '/assets/images/waste_management2.png',
    'Waste Management Transfer Station': '/assets/images/waste_management3.png',
    'Waste Management Reuse Shop': '/assets/images/waste_management4.png',
    'Waste Management Organics Recycling Facility': '/assets/images/waste_management5.png',
    'Waste Management E-Waste Drop-Off Facility': '/assets/images/waste_management6.png',
    'Waste Management Materials Recovery Facility': '/assets/images/waste_management7.png',
    'Waste Management Other Waste Facility': '/assets/images/waste_management8.png',
    'Waste Management Soft Plastics Drop-Off Facility': '/assets/images/waste_management9.png',
    'Waste Management Other Recycling Facility': '/assets/images/waste_management10.png',
    'Waste Management Unclassified Landfill': '/assets/images/waste_management11.png',
    'Waste Management Metals Recovery Facility': '/assets/images/waste_management12.png',
    'Waste Management Plastics Recovery Facility': '/assets/images/waste_management13.png',
    'Waste Management Plastics Processing Facility': '/assets/images/waste_management14.png',
    'Waste Management Paper Recycling Facility': '/assets/images/waste_management15.png',
    'Waste Management Rubber Recycling Facility': '/assets/images/waste_management16.png',
    'Waste Management Inert Landfill': '/assets/images/waste_management17.png',
    'Waste Management CDS Drop-Off Facility': '/assets/images/waste_management18.png',
    'Waste Management Other': '/assets/images/waste_management19.png',
    'Maritime Ports Commodity': '/assets/images/port1.png',
    'Maritime Ports Commodity & Military': '/assets/images/port2.png',
    'Mineral Deposits Mineral Deposit': '/assets/images/mineral_deposits1.png',
    'Mineral Deposits Historic Mine': '/assets/images/mineral_deposits2.png',
    'Mineral Deposits Mine Under Development': '/assets/images/mineral_deposits3.png',
    'Mineral Deposits Operating Mine': '/assets/images/mineral_deposits4.png',
    'Mineral Deposits Care and Maintenance': '/assets/images/mineral_deposits5.png',
    // Add more icons as needed
};